num1 = int(input("Enter the first number:"))
num2 = int(input("Enter the second number:"))
num3 = int(input("Enter the third number:"))
num4 = int(input("Enter the fourth number:"))
num5 = int(input("Enter the fifth number:"))
num6 = int(input("Enter the sixth number:"))
num7 = int(input("Enter the seveth number:"))
num8 = int(input("Enter the eight number:"))
myset = {num1,num2,num3,num4,num5,num6,num7,num8}     # We used set as we want all unique numbers once only.
print(myset)